/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.amuraru.opencensus.spark;

import org.junit.Test;
import static org.junit.Assert.*;

public class OpenCensusSinkTest {
    @Test public void testSomeLibraryMethod() {
//        OpenCensusSink classUnderTest = new OpenCensusSink();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
